---
title: "Covid-19 Updates (select regions)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

## Deaths per Day, 7-day Moving Average


```{r, echo=FALSE, warning=F, message=F}
library(tidyverse)
library(ggplot2)
library(plotly)
library(viridis)
data <- read_csv("regions.csv")
ggplotly(ggplot(data = data, mapping = aes(x = date, y = rollave7.deaths, color = region)) + geom_smooth(se=FALSE) + scale_y_log10() + theme_minimal() + scale_x_date(date_breaks = "1 week", date_labels = "%b %d", limits = c(as.Date("2020-02-15"), NA)) + labs(y = "7-day moving average", x = "Date", color = "Regions"))
```

## Cases per Day, 7-day Moving Average

```{r, echo=FALSE, warning=F, message=F}
data <- read_csv("regions.csv")
ggplotly(ggplot(data = data, mapping = aes(x = date, y = rollave7.cases, color = region)) + geom_smooth(se=FALSE) + scale_y_log10() + theme_minimal() + scale_x_date(date_breaks = "1 week", date_labels = "%b %d", limits = c(as.Date("2020-02-15"), NA)) + labs(y = "7-day moving average", x = "Date", color = "Regions"))
```