---
title: "Job Security Over Time - Descriptives"
author: "Kimberly Seung Goulart"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

```{r, echo=F, message=F, warning=F}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(haven)
library(beepr)
library(sjmisc)
library(ggpubr)
library(ggplot2)
library(plotly)

setwd("/Volumes/GoogleDrive/My Drive/Thesis/Paper3/data")
d <- readRDS("5cleaned.rds")


```

## Average Tenure Over Time by Countries (EU28)

```{r, echo=FALSE, message=FALSE, warning=FALSE}

countrytable <- d %>%
  group_by(country,year) %>%
  summarise(meantenure = weighted.mean(tenure, w4, na.rm = T),
            count = n(),
            se = sd(tenure, na.rm = T)/sqrt(count)) %>%
  na.omit()

alltable <- d %>% 
  group_by(year) %>% 
  summarise(meantenure = weighted.mean(tenure, w5, na.rm = T),
            count = n(),
            se = sd(tenure, na.rm = T)/sqrt(count)) %>% 
  mutate(country = "All") %>% 
  ungroup()

countrytable <- countrytable %>% 
  bind_rows(alltable)

ggplot(countrytable, aes(year,meantenure)) + 
  geom_line() + 
  geom_point() +
  geom_errorbar(aes(ymin=meantenure-se, ymax=meantenure+se), width=.2, position=position_dodge(0.05)) +
  labs(x = "Year", y = "Weighted Average Tenure") +
  facet_wrap(~country)

```


## Average Tenure Over Time by Gender (EU28)

```{r, echo=FALSE, message=FALSE, warning=FALSE}

gendertable <- d %>%
  group_by(country,sex,year) %>%
  summarise(meantenure = weighted.mean(tenure, w4, na.rm = T),
            count = n(),
            se = sd(tenure, na.rm = T)/sqrt(count)) %>%
  na.omit()

alltable <- d %>% 
  group_by(sex, year) %>% 
  summarise(meantenure = weighted.mean(tenure, w5, na.rm = T),
            count = n(),
            se = sd(tenure, na.rm = T)/sqrt(count)) %>% 
  na.omit() %>% 
  mutate(country = "All") %>% 
  ungroup()

gendertable <- gendertable %>% 
  bind_rows(alltable)


ggplot(gendertable, aes(year,meantenure, group = sex, colour = sex)) + 
  geom_line() + 
  geom_point() +
  geom_errorbar(aes(ymin=meantenure-se, ymax=meantenure+se), width=.2, position=position_dodge(0.05)) +
  labs(x = "Year", y = "Weighted Average Tenure") +
  facet_wrap(~country)



```


## Models

```{r, echo=FALSE, message=FALSE, warning=FALSE}



```

